// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmI1xTU0-j2zlrOt9-HHQqwO1W_rc3oSc',
    appId: '1:506290336225:web:63faba26a2466c92b022a0',
    messagingSenderId: '506290336225',
    projectId: 'fir-123-60723',
    authDomain: 'fir-123-60723.firebaseapp.com',
    storageBucket: 'fir-123-60723.firebasestorage.app',
    databaseURL: 'https://fir-123-60723-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6MDf8QFkiR7JJcmb7htF4f46muqffig',
    appId: '1:506290336225:android:e813b0abd36fd4e1b022a0',
    messagingSenderId: '506290336225',
    projectId: 'fir-123-60723',
    storageBucket: 'fir-123-60723.firebasestorage.app',
    databaseURL: 'https://fir-123-60723-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmI1xTU0-j2zlrOt9-HHQqwO1W_rc3oSc',
    appId: '1:506290336225:web:b45c5b79d4825a0eb022a0',
    messagingSenderId: '506290336225',
    projectId: 'fir-123-60723',
    authDomain: 'fir-123-60723.firebaseapp.com',
    storageBucket: 'fir-123-60723.firebasestorage.app',
    databaseURL: 'https://fir-123-60723-default-rtdb.firebaseio.com/'
  );
}
